### ISSUE TITLE
Error when using vertical flag

### ISSUE THREAD

**Issue by jamesrwhite** [mkaz/termgraph#58]
Hi,

I'm seeing the following error when I try and graph this data vertically using the `--vertical` cli flag. If I run it without the vertical flag it works fine.

**Data:**
```csv
12/05/2020,3
13/05/2020,10
14/05/2020,14
15/05/2020,22
16/05/2020,17
17/05/2020,19
18/05/2020,24
```

**Command:**
```bash
termgraph data.csv --vertical
```

**Error:**
```
Traceback (most recent call last):
  File "/Users/james/.local/share/virtualenvs/metrics-aYLqKSM2/bin/termgraph", line 8, in <module>
    sys.exit(main())
  File "/Users/james/.local/share/virtualenvs/metrics-aYLqKSM2/lib/python3.8/site-packages/termgraph/termgraph.py", line 161, in main
    chart(colors, data, args, labels)
  File "/Users/james/.local/share/virtualenvs/metrics-aYLqKSM2/lib/python3.8/site-packages/termgraph/termgraph.py", line 424, in chart
    vertic = vertically(*row, args=args)
TypeError: vertically() got multiple values for argument 'args'
```

I'm using Python `v3.8.2` and termgraph `v0.2.2`.

Let me know if there's any more info I can provide.

**Comment by mkaz** [comment]
Thanks for the bug report, I was able to duplicate with the data provided. 
I'll try to look some time soon to dig and refresh my memory on what all is happening in the code

**Comment by jamesrwhite** [comment]
Works for me on the latest release now, thanks! 🎉
